spring.application.name=backend
spring.datasource.url=jdbc:dbeaver:libsql:libsql://userdata1-cappytheecom.aws-us-east-2.turso.io
spring.datasource.username=
spring.datasource.password=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NzkxODA0NDMsImlkIjoiMDE5ZTNmNjctMjMwMS03N2IwLTgzMjItZjQzNmM1M2Q3ZjUwIiwicmlkIjoiZjJhOTE4NGMtMzJmYi00MjIxLWIzYmUtMmY3ZjU2ZjQwNTFiIn0.DhWWP_afGkqvwOmS4VmrErMX5re4e4RxGryAJTgFrYR7gaINq-gqAsu85wNIh-RSSNqERzccd4zqkwqJ8T3tAQ
spring.datasource.driver-class-name=com.dbeaver.jdbc.driver.libsql.LibSqlDriver

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update